// reviewsData.ts
export const reviews = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "Project Manager at TechCorp",
    rating: 5,
    text: "Working with Amjad has been an absolute pleasure. His expertise in front-end technologies and commitment to delivering high-quality work is unmatched. He consistently exceeded our expectations.",
    img: "/assets/images/1.jpg",
  },
  {
    id: 2,
    name: "David Smith",
    role: "CTO at InnovateX",
    rating: 5,
    text: "Amjad is a highly skilled full-stack developer who brings creativity and problem-solving skills to every project. His ability to work across the entire stack ensured our project was a success.",
    img: "/assets/images/1.jpg",
  },
  {
    id: 3,
    name: "Emily Davis",
    role: "Product Owner at Creative Solutions",
    rating: 4,
    text: "Amjad's attention to detail and dedication to delivering a perfect product resulted in a flawless user experience for our app. His ability to meet tight deadlines was greatly appreciated.",
    img: "/assets/images/1.jpg",
  },
  {
    id: 4,
    name: "Michael Brown",
    role: "Senior Developer at CodeWorks",
    rating: 5,
    text: "Collaborating with Amjad was an excellent experience. His deep understanding of both front-end and back-end development allowed us to tackle complex features with ease.",
    img: "/assets/images/1.jpg",
  },
  {
    id: 5,
    name: "Alice Williams",
    role: "CEO at NextGen Tech",
    rating: 5,
    text: "Amjad’s skills in web development are top-notch. He transformed our outdated website into a modern, user-friendly platform that has greatly improved our customer engagement.",
    img: "/assets/images/1.jpg",
  },
  {
    id: 6,
    name: "James Martin",
    role: "Lead Designer at PixelPerfect",
    rating: 4,
    text: "Amjad is a fantastic developer to work with. His collaboration and integration of design and functionality made our project a huge success. His coding skills are exceptional.",
    img: "/assets/images/1.jpg",
  },
  {
    id: 7,
    name: "Olivia Harris",
    role: "Tech Lead at DevSolutions",
    rating: 5,
    text: "Amjad’s comprehensive knowledge of both front-end and back-end development is impressive. He took our project to the next level with his innovative approach and expertise.",
    img: "/assets/images/1.jpg",
  },
  {
    id: 8,
    name: "Robert Clark",
    role: "Product Manager at SoftCorp",
    rating: 5,
    text: "Amjad is a dedicated and highly skilled developer. His contribution to our project was invaluable, and he always ensured that the quality was top-notch. Highly recommended!",
    img: "/assets/images/1.jpg",
  },
];
